### ISSUE TITLE
Latest version of master failing 

### ISSUE THREAD

**Issue by cslatteryjbc** [chrism0dwk/covid-pipeline#1]
The latest version of master fails immediately. Tested by building/running the Dockerfile and by running manually.

Error output:
```
2021-08-02 12:55:01.372410: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-08-02 12:55:01.372434: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ec2-user/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/SageMaker/jbc-kauai/covid-pipeline/covid_pipeline/pipeline.py", line 8, in <module>
    from covid_pipeline.ruffus_pipeline import run_pipeline
  File "/home/ec2-user/SageMaker/jbc-kauai/covid-pipeline/covid_pipeline/ruffus_pipeline.py", line 24, in <module>
    from covid_pipeline.tasks import (
  File "/home/ec2-user/SageMaker/jbc-kauai/covid-pipeline/covid_pipeline/tasks/__init__.py", line 13, in <module>
    from covid_pipeline.tasks.lancs_risk_report import report_lancs as lancs_risk_report
ModuleNotFoundError: No module named 'covid_pipeline.tasks.lancs_risk_report'
```

**Comment by chrism0dwk** [comment]
Apologies for the delay.  This should be fixed in 720d66d.  Please could you verify for me?

**Comment by cslatteryjbc** [comment]
Thanks.  Will check shortly

**Comment by cslatteryjbc** [comment]
FYI, New error:
```
Original exception:

    Exception #1
      'builtins.KeyError('initial_rates')' raised in ...
       Task = def covid_pipeline.ruffus_pipeline.run_mcmc(...):
       Job  = [/results/inferencedata.nc -> /results/posterior.hd5, map]
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/dist-packages/ruffus/task.py", line 713, in run_pooled_job_without_exceptions
        register_cleanup, touch_files_only)
      File "/usr/local/lib/python3.7/dist-packages/ruffus/task.py", line 545, in job_wrapper_io_files
        ret_val = user_defined_work_func(*params)
      File "/app/covid_pipeline/ruffus_pipeline.py", line 87, in run_mcmc
        mcmc(input_file, output_file, config["Mcmc"])
      File "/usr/local/lib/python3.7/dist-packages/covid19uk/inference/inference.py", line 493, in mcmc
        config['initial_rates']['ei'],
    KeyError: 'initial_rates'
```

Tested with a different config file -  uk_config.yaml and the job appears to be running fine.  The default config is just missing the 'initial_rates' keys.

**Comment by cslatteryjbc** [comment]
The latest version also fails to use gpu 
```
2021-08-10 13:08:05.942516: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2021-08-10 13:08:05.942788: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2021-08-10 13:08:05.943542: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2021-08-10 13:08:05.943721: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2021-08-10 13:08:05.943748: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
```
I am currently testing upgrading the base image to cuda11.2.2

**Comment by chrism0dwk** [comment]
@cslatteryjbc as you've identified, this looks like you've got CUDA <11.2 installed.  The new build uses TF2.5, which [demands CUDA==11.2](https://www.tensorflow.org/install/gpu).

HTH
